--
-- Table structure for table T_COM_COMPANY
--

CREATE TABLE T_COM_COMPANY (
  ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  BUSINESSNAME VARCHAR(200) DEFAULT NULL,
  ACTIVE INTEGER DEFAULT NULL,
  DOCNUMBER VARCHAR(11) DEFAULT NULL,
  DOMAIN VARCHAR(10) DEFAULT NULL,
  PRIMARY KEY (ID)
);


CREATE UNIQUE INDEX T_COM_COMPANY_DOMAIN_UNIQUE ON T_COM_COMPANY(DOMAIN);

--
-- Table structure for table T_EMP_AREA
--

CREATE TABLE T_COM_AREA (
  ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  COMPANYID INTEGER NOT NULL,
  NAME VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_REL_AREA_COMPANY FOREIGN KEY (COMPANYID) REFERENCES T_COM_COMPANY (ID)
);


--
-- Table structure for table T_SEG_ROLE
--

CREATE TABLE T_SEG_ROLE (
  ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  COMPANYID INTEGER NOT NULL,
  AREAID INTEGER NOT NULL,
  NAME VARCHAR(50) DEFAULT NULL,
  DESCRIPTION VARCHAR(300) DEFAULT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_REL_ROLE_COMPANY FOREIGN KEY (COMPANYID) REFERENCES T_COM_COMPANY (ID),
  CONSTRAINT FK_REL_ROLE_AREA FOREIGN KEY (AREAID) REFERENCES T_COM_AREA (ID)
);


--
-- Table structure for table T_SEG_USER
--

CREATE TABLE T_SEG_USER (
  ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  COMPANYID INTEGER NOT NULL,
  PASSWORD VARCHAR(150) DEFAULT NULL,
  USERNAME VARCHAR(45) DEFAULT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_REL_USER_COMPANY FOREIGN KEY (COMPANYID) REFERENCES T_COM_COMPANY (ID)
);


--
-- Table structure for table T_SEG_MODULE
--

CREATE TABLE T_SEG_MODULE (
  ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  COMPANYID INTEGER NOT NULL,
  DESCRIPTION VARCHAR(50) DEFAULT NULL,
  RESOURCE VARCHAR(45) DEFAULT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_REL_MODULE_COMPANY FOREIGN KEY (COMPANYID) REFERENCES T_COM_COMPANY (ID)
);


--
-- Table structure for table T_SEG_ROLE2MODULE
--

CREATE TABLE T_SEG_ROLE2MODULE (
  ROLEID INTEGER NOT NULL,
  MODULEID INTEGER NOT NULL,
  ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
  PRIMARY KEY (ROLEID,MODULEID),
  CONSTRAINT FK_T_SEG_ROLE2MODULE FOREIGN KEY (ROLEID) REFERENCES T_SEG_ROLE (ID),
  CONSTRAINT FK_T_SEG_ROLE2MODULE_1 FOREIGN KEY (MODULEID) REFERENCES T_SEG_MODULE (ID)
);


--
-- Table structure for table T_BUS_PARAMTYPE
--

CREATE TABLE T_BUS_PARAMTYPE (
  ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  COMPANYID INTEGER NOT NULL,
  NAME VARCHAR(50) NOT NULL,
  DESCRIPTION VARCHAR(150) DEFAULT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_REL_PARAMTYPE_COMPANY FOREIGN KEY (COMPANYID) REFERENCES T_COM_COMPANY (ID)
);


--
-- Table structure for table T_BUS_PARAMETER
--

CREATE TABLE T_BUS_PARAMETER (
  ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  COMPANYID INTEGER NOT NULL,
  PARAMTYPEID INTEGER NOT NULL,
  NAME VARCHAR(50) NOT NULL,
  DESCRIPTION VARCHAR(150) DEFAULT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_REL_PARAMETER_COMPANY FOREIGN KEY (COMPANYID) REFERENCES T_COM_COMPANY (ID),
  CONSTRAINT FK_REL_PARAMETER_PARAMTYPE FOREIGN KEY (PARAMTYPEID) REFERENCES T_BUS_PARAMTYPE (ID)
);

--
-- Table structure for table T_BUS_EMPLOYEE
--

CREATE TABLE T_BUS_EMPLOYEE (
  ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  ROLEID INTEGER NOT NULL,
  USERID INTEGER NOT NULL,
  COMPANYID INTEGER NOT NULL,
  NAME VARCHAR(50) NOT NULL,
  LASTNAME VARCHAR(50) NOT NULL,
  LASTNAME2 VARCHAR(50) DEFAULT NULL,
  DOCTYPEID INTEGER NOT NULL,
  DOCNUMBER VARCHAR(15) NOT NULL,
  ADDRESS VARCHAR(70) DEFAULT NULL,
  PHONE VARCHAR(15) DEFAULT NULL,
  CELLPHONE VARCHAR(20) DEFAULT NULL,
  EMAIL VARCHAR(30) NOT NULL,
  CITY VARCHAR(20) DEFAULT NULL,
  UBIGEO VARCHAR(20) DEFAULT NULL,
  BIRTHDAY DATE NOT NULL,
  ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
  PRIMARY KEY (ID),
  CONSTRAINT FK_REL_EMPLOYEE_ROLE FOREIGN KEY (ROLEID) REFERENCES T_SEG_ROLE (ID),
  CONSTRAINT FK_REL_EMPLOYEE_USER FOREIGN KEY (USERID) REFERENCES T_SEG_USER (ID),
  CONSTRAINT FK_REL_EMPLOYEE_COMPANY FOREIGN KEY (COMPANYID) REFERENCES T_COM_COMPANY (ID),
  CONSTRAINT FK_REL_EMPLOYEE_DOCTYPE FOREIGN KEY (DOCTYPEID) REFERENCES T_BUS_PARAMETER (ID)
) ;


--
-- Table structure for table T_BUS_CATEGORY
--

CREATE TABLE T_BUS_CATEGORY (
  ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  COMPANYID INTEGER NOT NULL,
  NAME VARCHAR(60) DEFAULT NULL,
  ACTIVE BOOLEAN DEFAULT TRUE NOT NULL,
  PARENTID INTEGER,
  IMAGE VARCHAR(45) DEFAULT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_REL_CATEGORY_COMPANY FOREIGN KEY (COMPANYID) REFERENCES T_COM_COMPANY (ID),
  CONSTRAINT FK_REL_CATEGORY_CATEGORY FOREIGN KEY (PARENTID) REFERENCES T_BUS_CATEGORY (ID)
);

CREATE TABLE T_BUS_ATRIBUTO (
  ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  COMPANYID INTEGER NOT NULL,
  NOMBRE VARCHAR(20) NOT NULL,
  DESCR VARCHAR(80),
  ACTIVO INTEGER DEFAULT 1,
  FILTRABLE INTEGER DEFAULT 0,
  --PREDET INTEGER DEFAULT NULL,    --Para el precio por ejemplo, que debe existir si o si.
  CATEGORYID INTEGER,
  PRIMARY KEY (ID),
  CONSTRAINT FK_REL_ATRIBUTO_CATEGORY FOREIGN KEY (CATEGORYID) REFERENCES T_BUS_CATEGORY (ID)
);

--
-- Table structure for table T_BUS_TRADEMARK
--

CREATE TABLE T_BUS_TRADEMARK (
  ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  COMPANYID INTEGER NOT NULL,
  NAME VARCHAR(70) NOT NULL,
  ACTIVE BOOLEAN DEFAULT TRUE NOT NULL,
  IMAGE VARCHAR(45) DEFAULT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_REL_TRADEMARK_COMPANY FOREIGN KEY (COMPANYID) REFERENCES T_COM_COMPANY (ID)
);

CREATE TABLE T_BUS_PRODUCT (
  ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  COMPANYID INTEGER NOT NULL,
  NAME VARCHAR(70) DEFAULT NULL,
  TRADEMARKID INTEGER NOT NULL,
  DESCRIPTION VARCHAR(4000) DEFAULT NULL,
  --ARTICULO_N_PRECIO DOUBLE PRECISION DEFAULT NULL,
  --ARTICULO_N_STOCK INTEGER DEFAULT 0,
  ACTIVE BOOLEAN DEFAULT TRUE NOT NULL,
  --IMAGE VARCHAR(45) DEFAULT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_REL_ARTICULO_COMPANY FOREIGN KEY (COMPANYID) REFERENCES T_COM_COMPANY (ID),
  CONSTRAINT FK_REL_ARTICULO_TRADEMARK FOREIGN KEY (TRADEMARKID) REFERENCES T_BUS_TRADEMARK (ID)
);

CREATE TABLE T_BUS_PRODUCTIMAGE (
  ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  COMPANYID INTEGER NOT NULL,
  NAME VARCHAR(70) NOT NULL,
  PRODUCTID INTEGER NOT NULL,
  IMAGDEFAULT BOOLEAN DEFAULT FALSE NOT NULL,
  ACTIVE BOOLEAN DEFAULT TRUE NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_REL_PRODUCTIMAGE_COMPANY FOREIGN KEY (COMPANYID) REFERENCES T_COM_COMPANY (ID),
  CONSTRAINT FK_REL_PRODUCTIMAGE_ARTICULO FOREIGN KEY (PRODUCTID) REFERENCES T_BUS_PRODUCT (ID)
);

CREATE TABLE T_BUS_ARTIC2ATRIB (
  ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  COMPANYID INTEGER NOT NULL,
  PRODUCTID INTEGER NOT NULL,
  ATTRIBUTEID INTEGER NOT NULL,
  NOMBRE VARCHAR(20) NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_REL_DESDE_ARTICULO FOREIGN KEY (PRODUCTID) REFERENCES T_BUS_PRODUCT (ID),
  CONSTRAINT FK_REL_HASTA_ATRIBUTO FOREIGN KEY (ATTRIBUTEID) REFERENCES T_BUS_ATRIBUTO (ID)
);

CREATE TABLE T_BUS_INVENTARIO (
  ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  COMPANYID INTEGER NOT NULL,
  PRODUCTID INTEGER NOT NULL,
  STOCK DOUBLE,
  RESERVA DOUBLE,
  FECHA DATE,
  PRIMARY KEY (ID),
  CONSTRAINT FK_REL_INVENTARIO_ARTICULO FOREIGN KEY (PRODUCTID) REFERENCES T_BUS_PRODUCT (ID)
);

CREATE TABLE T_BUS_PRECIO (
  ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  PRODUCTID INTEGER NOT NULL,
  DESDE DATE,
  HASTA DATE,
  MONTO DOUBLE,
  PRIMARY KEY (ID),
  CONSTRAINT FK_REL_PRECIO_ARTICULO FOREIGN KEY (PRODUCTID) REFERENCES T_BUS_PRODUCT (ID)
);

CREATE TABLE T_BUS_COSTO (
  ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  PRODUCTID INTEGER NOT NULL,
  DESDE DATE,
  HASTA DATE,
  MONTO DOUBLE,
  PRIMARY KEY (ID),
  CONSTRAINT FK_REL_COSTO_ARTICULO FOREIGN KEY (PRODUCTID) REFERENCES T_BUS_PRODUCT (ID)
);

CREATE TABLE T_BUS_OFERTA (
  ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  PRODUCTID INTEGER NOT NULL,
  DESDE DATE,
  HASTA DATE,
  MONTO DOUBLE,
  PRIMARY KEY (ID),
  CONSTRAINT FK_REL_OFERTA_ARTICULO FOREIGN KEY (PRODUCTID) REFERENCES T_BUS_PRODUCT (ID)
);

CREATE TABLE T_BUS_CATEG2ARTIC (
  ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  CATEGORYID INTEGER NOT NULL,
  PRODUCTID INTEGER NOT NULL,
  CONSTRAINT FK_REL_CATEGORY_FROM FOREIGN KEY (CATEGORYID) REFERENCES T_BUS_CATEGORY (ID),
  CONSTRAINT FK_REL_ARTICULO_TO FOREIGN KEY (PRODUCTID) REFERENCES T_BUS_PRODUCT (ID)
);

--
-- Table structure for table T_BUS_CLIENT
--

CREATE TABLE T_BUS_CLIENT (
  ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  COMPANYID INTEGER NOT NULL,
  USERID INTEGER NOT NULL,
  NAME VARCHAR(60) NOT NULL,
  LASTNAME VARCHAR(60) NOT NULL,
  LASTNAME2 VARCHAR(60) DEFAULT NULL,
  BIRTHDAY DATE DEFAULT NULL,
  DOCTYPEID INTEGER DEFAULT NULL,
  DOCNUMBER VARCHAR(15) DEFAULT NULL,
  ADDRESS VARCHAR(80) DEFAULT NULL,
  PHONE VARCHAR(10) DEFAULT NULL,
  CELLPHONE VARCHAR(10) DEFAULT NULL,
  EMAIL VARCHAR(30) NOT NULL,
  CITY VARCHAR(20) DEFAULT NULL,
  UBIGEO VARCHAR(6) DEFAULT NULL,
  POSTCODE VARCHAR(6) DEFAULT NULL,
  ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
  PRIMARY KEY (ID),
  CONSTRAINT FK_REL_CLIENT_USER FOREIGN KEY (USERID) REFERENCES T_SEG_USER (ID),
  CONSTRAINT FK_REL_CLIENT_CLIENT FOREIGN KEY (COMPANYID) REFERENCES T_COM_COMPANY (ID),
  CONSTRAINT FK_REL_CLIENT_DOCTYPE FOREIGN KEY (DOCTYPEID) REFERENCES T_BUS_PARAMETER (ID)
);

--
-- Table structure for table T_BUS_PEDIDO_TIPO
--

CREATE TABLE T_BUS_PEDIDO_TIPO (
  TIPOPED_N_CODIGO INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  TIPOPED_V_DESCRIPCION VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (TIPOPED_N_CODIGO)
);

--
-- Table structure for table T_BUS_PEDIDO
--

CREATE TABLE T_BUS_PEDIDO (
  PEDIDO_N_CODIGO INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  COMPANYID INTEGER NOT NULL,
  CLIENTID INTEGER NOT NULL,
  TIPOPED_N_CODIGO INTEGER NOT NULL,
  PEDIDO_D_FECHA DATE DEFAULT NULL,
  PEDIDO_N_IGV INTEGER DEFAULT NULL,
  PEDIDO_N_TOTAL DOUBLE PRECISION DEFAULT NULL,
  PRIMARY KEY (PEDIDO_N_CODIGO),
  CONSTRAINT FK_REL_COMPANY_PEDIDO FOREIGN KEY (COMPANYID) REFERENCES T_COM_COMPANY (ID),
  CONSTRAINT FK_REL_PEDIDO_CLIENTE FOREIGN KEY (CLIENTID) REFERENCES T_BUS_CLIENT (ID),
  CONSTRAINT FK_REL_PEDIDO_TIPO FOREIGN KEY (TIPOPED_N_CODIGO) REFERENCES T_BUS_PEDIDO_TIPO (TIPOPED_N_CODIGO)
);


--
-- Table structure for table T_BUS_PEDIDO2PEDIDO
--

CREATE TABLE T_BUS_PEDIDO2PEDIDO (
  PEDIDO_N_CODIGO_FROM INTEGER NOT NULL,
  PEDIDO_N_CODIGO_TO INTEGER NOT NULL,
  PRIMARY KEY (PEDIDO_N_CODIGO_FROM,PEDIDO_N_CODIGO_TO)
);


--
-- Table structure for table T_BUS_PEDIDO_DET
--

CREATE TABLE T_BUS_PEDIDO_DET (
  PEDIDO_N_CODIGO INTEGER NOT NULL,
  ARTICULO_N_CODIGO INTEGER NOT NULL,
  DETPED_N_CANTIDAD INTEGER DEFAULT NULL,
  PRIMARY KEY (PEDIDO_N_CODIGO,ARTICULO_N_CODIGO),
  CONSTRAINT FK_T_BUS_PEDIDO_DET FOREIGN KEY (PEDIDO_N_CODIGO) REFERENCES T_BUS_PEDIDO (PEDIDO_N_CODIGO),
  CONSTRAINT FK_T_BUS_PEDIDO_DET2 FOREIGN KEY (ARTICULO_N_CODIGO) REFERENCES T_BUS_PRODUCT (ID)
);


--
-- Table structure for table T_BUS_SOLICITUD
--

CREATE TABLE T_BUS_SOLICITUD (
  SOLICITUD_N_CODIGO INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  SOLICITUD_V_RAZON VARCHAR(100) DEFAULT NULL,
  SOLICITUD_N_RUC VARCHAR(11) DEFAULT NULL,
  SOLICITUD_D_FECHA DATE DEFAULT NULL,
  SOLICITUD_N_ESTADO INTEGER DEFAULT NULL,
  SOLICITUD_V_EMAIL VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (SOLICITUD_N_CODIGO)
);


--
-- Table structure for table T_BUS_VENTA_TIPO
--

CREATE TABLE T_BUS_VENTA_TIPO (
  TIPOVEN_N_CODIGO INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  COMPANYID INTEGER NOT NULL,
  TIPOVEN_V_DESCRIPCION VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (TIPOVEN_N_CODIGO),
  CONSTRAINT FK_REL_COMPANY_TIPOVENTA FOREIGN KEY (COMPANYID) REFERENCES T_COM_COMPANY (ID)
);
