--
-- Table structure for table T_COM_COMPANY
--

CREATE TABLE T_COM_COMPANY (
  ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  BUSINESSNAME VARCHAR(200) DEFAULT NULL,
  ACTIVE INTEGER DEFAULT NULL,
  DOCNUMBER VARCHAR(11) DEFAULT NULL,
  DOMAIN VARCHAR(10) DEFAULT NULL,
  PRIMARY KEY (ID)
);


CREATE UNIQUE INDEX T_COM_COMPANY_DOMAIN_UNIQUE ON T_COM_COMPANY(DOMAIN);

--
-- Table structure for table T_EMP_AREA
--

CREATE TABLE T_COM_AREA (
  ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  COMPANYID BIGINT NOT NULL,
  NAME VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_REL_AREA_COMPANY FOREIGN KEY (COMPANYID) REFERENCES T_COM_COMPANY (ID)
);


--
-- Table structure for table T_SEG_ROLE
--

CREATE TABLE T_SEG_ROLE (
  ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  COMPANYID BIGINT NOT NULL,
  AREAID BIGINT NOT NULL,
  NAME VARCHAR(50) DEFAULT NULL,
  DESCRIPTION VARCHAR(300) DEFAULT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_REL_ROLE_COMPANY FOREIGN KEY (COMPANYID) REFERENCES T_COM_COMPANY (ID),
  CONSTRAINT FK_REL_ROLE_AREA FOREIGN KEY (AREAID) REFERENCES T_COM_AREA (ID)
);


--
-- Table structure for table T_SEG_USER
--

CREATE TABLE T_SEG_USER (
  ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  COMPANYID BIGINT NOT NULL,
  PASSWORD VARCHAR(150) DEFAULT NULL,
  USERNAME VARCHAR(45) DEFAULT NULL,
  FIRSTNAME VARCHAR(20),
  LASTNAME VARCHAR(20),
  ROLEID BIGINT NOT NULL,
  LOCALE VARCHAR(5) NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_REL_USER_COMPANY FOREIGN KEY (COMPANYID) REFERENCES T_COM_COMPANY (ID),
  CONSTRAINT FK_REL_USER_ROLE FOREIGN KEY (ROLEID) REFERENCES T_SEG_ROLE (ID)
);


--
-- Table structure for table T_SEG_MODULE
--

CREATE TABLE T_SEG_MODULE (
  ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  COMPANYID BIGINT NOT NULL,
  DESCRIPTION VARCHAR(80) DEFAULT NULL,
  RESOURCE VARCHAR(45) DEFAULT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_REL_MODULE_COMPANY FOREIGN KEY (COMPANYID) REFERENCES T_COM_COMPANY (ID)
);


--
-- Table structure for table T_SEG_ROLE2MODULE
--

CREATE TABLE T_SEG_ROLE2MODULE (
  ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  ROLEID BIGINT NOT NULL,
  MODULEID BIGINT NOT NULL,
  ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
  PRIMARY KEY (ID),
  CONSTRAINT FK_T_SEG_ROLE2MODULE FOREIGN KEY (ROLEID) REFERENCES T_SEG_ROLE (ID),
  CONSTRAINT FK_T_SEG_ROLE2MODULE_1 FOREIGN KEY (MODULEID) REFERENCES T_SEG_MODULE (ID)
);


--
-- Table structure for table T_BUS_PARAMTYPE
--

CREATE TABLE T_BUS_PARAMTYPE (
  ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  COMPANYID BIGINT NOT NULL,
  NAME VARCHAR(50) NOT NULL,
  DESCRIPTION VARCHAR(150) DEFAULT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_REL_PARAMTYPE_COMPANY FOREIGN KEY (COMPANYID) REFERENCES T_COM_COMPANY (ID)
);


--
-- Table structure for table T_BUS_PARAMETER
--

CREATE TABLE T_BUS_PARAMETER (
  ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  COMPANYID BIGINT NOT NULL,
  PARAMTYPEID BIGINT NOT NULL,
  NAME VARCHAR(50) NOT NULL,
  DESCRIPTION VARCHAR(150) DEFAULT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_REL_PARAMETER_COMPANY FOREIGN KEY (COMPANYID) REFERENCES T_COM_COMPANY (ID),
  CONSTRAINT FK_REL_PARAMETER_PARAMTYPE FOREIGN KEY (PARAMTYPEID) REFERENCES T_BUS_PARAMTYPE (ID)
);

--
-- Table structure for table T_BUS_UBICACION
--

CREATE TABLE T_BUS_UBICATION (
  ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  PARENTID BIGINT,
  NAME VARCHAR(60) NOT NULL,
  CODE VARCHAR(6),
  PRIMARY KEY (ID)--,
  --CONSTRAINT FK_REL_UBICACION_PARENTID FOREIGN KEY (PARENTID) REFERENCES T_BUS_UBICACION (ID)
);
ALTER TABLE T_BUS_UBICATION ADD CONSTRAINT FK_REL_UBICACION_PARENTID FOREIGN KEY (PARENTID) REFERENCES T_BUS_UBICATION(ID);

--
-- Table structure for table T_BUS_EMPLOYEE
--

CREATE TABLE T_BUS_EMPLOYEE (
  ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  USERID BIGINT DEFAULT NULL,
  COMPANYID BIGINT NOT NULL,
  NAME VARCHAR(50) NOT NULL,
  LASTNAME VARCHAR(50) NOT NULL,
  LASTNAME2 VARCHAR(50) DEFAULT NULL,
  DOCTYPEID BIGINT NOT NULL,
  DOCNUMBER VARCHAR(15) NOT NULL,
  ADDRESS VARCHAR(70) DEFAULT NULL,
  PHONE VARCHAR(15) DEFAULT NULL,
  CELLPHONE VARCHAR(20) DEFAULT NULL,
  EMAIL VARCHAR(30) NOT NULL,
  CITY VARCHAR(20) DEFAULT NULL,
  UBIGEO VARCHAR(6) DEFAULT NULL,
  DEPARTMENTID BIGINT DEFAULT NULL,
  PROVINCEID BIGINT DEFAULT NULL,
  DISTRICTID BIGINT DEFAULT NULL,
  BIRTHDAY DATE NOT NULL,
  SEXID BIGINT NOT NULL,
  CIVILSTATEID BIGINT,
  ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
  PRIMARY KEY (ID),
  CONSTRAINT FK_REL_EMPLOYEE_USER FOREIGN KEY (USERID) REFERENCES T_SEG_USER (ID),
  CONSTRAINT FK_REL_EMPLOYEE_COMPANY FOREIGN KEY (COMPANYID) REFERENCES T_COM_COMPANY (ID),
  CONSTRAINT FK_REL_EMPLOYEE_DOCTYPE FOREIGN KEY (DOCTYPEID) REFERENCES T_BUS_PARAMETER (ID),
  CONSTRAINT FK_REL_EMPLOYEE_SEX FOREIGN KEY (SEXID) REFERENCES T_BUS_PARAMETER (ID),
  CONSTRAINT FK_REL_EMPLOYEE_CIVILSTATE FOREIGN KEY (CIVILSTATEID) REFERENCES T_BUS_PARAMETER (ID),
  CONSTRAINT FK_REL_EMPLOYEE_DEPARTMENT FOREIGN KEY (DEPARTMENTID) REFERENCES T_BUS_UBICATION (ID),
  CONSTRAINT FK_REL_EMPLOYEE_PROVINCE FOREIGN KEY (PROVINCEID) REFERENCES T_BUS_UBICATION (ID),
  CONSTRAINT FK_REL_EMPLOYEE_DISTRICT FOREIGN KEY (DISTRICTID) REFERENCES T_BUS_UBICATION (ID)
) ;


--
-- Table structure for table T_BUS_CATEGORY
--

CREATE TABLE T_BUS_CATEGORY (
  ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  COMPANYID BIGINT NOT NULL,
  NAME VARCHAR(60) DEFAULT NULL,
  ACTIVE BOOLEAN DEFAULT TRUE NOT NULL,
  PARENTID BIGINT,
  IMAGE VARCHAR(45) DEFAULT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_REL_CATEGORY_COMPANY FOREIGN KEY (COMPANYID) REFERENCES T_COM_COMPANY (ID),
  CONSTRAINT FK_REL_CATEGORY_CATEGORY FOREIGN KEY (PARENTID) REFERENCES T_BUS_CATEGORY (ID)
);

CREATE TABLE T_BUS_ATRIBUTO (
  ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  COMPANYID BIGINT NOT NULL,
  NOMBRE VARCHAR(20) NOT NULL,
  DESCR VARCHAR(80),
  ACTIVO INTEGER DEFAULT 1,
  FILTRABLE INTEGER DEFAULT 0,
  --PREDET INTEGER DEFAULT NULL,    --Para el precio por ejemplo, que debe existir si o si.
  CATEGORYID BIGINT,
  PRIMARY KEY (ID),
  CONSTRAINT FK_REL_ATRIBUTO_CATEGORY FOREIGN KEY (CATEGORYID) REFERENCES T_BUS_CATEGORY (ID)
);

--
-- Table structure for table T_BUS_TRADEMARK
--

CREATE TABLE T_BUS_TRADEMARK (
  ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  COMPANYID BIGINT NOT NULL,
  NAME VARCHAR(70) NOT NULL,
  ACTIVE BOOLEAN DEFAULT TRUE NOT NULL,
  IMAGE VARCHAR(45) DEFAULT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_REL_TRADEMARK_COMPANY FOREIGN KEY (COMPANYID) REFERENCES T_COM_COMPANY (ID)
);

CREATE TABLE T_BUS_PRODUCT (
  ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  COMPANYID BIGINT NOT NULL,
  NAME VARCHAR(70) DEFAULT NULL,
  TRADEMARKID BIGINT NOT NULL,
  DESCRIPTION VARCHAR(4000) DEFAULT NULL,
  --ARTICULO_N_PRECIO DOUBLE PRECISION DEFAULT NULL,
  --ARTICULO_N_STOCK INTEGER DEFAULT 0,
  ACTIVE BOOLEAN DEFAULT TRUE NOT NULL,
  --IMAGE VARCHAR(45) DEFAULT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_REL_ARTICULO_COMPANY FOREIGN KEY (COMPANYID) REFERENCES T_COM_COMPANY (ID),
  CONSTRAINT FK_REL_ARTICULO_TRADEMARK FOREIGN KEY (TRADEMARKID) REFERENCES T_BUS_TRADEMARK (ID)
);

CREATE TABLE T_BUS_PRODUCTIMAGE (
  ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  COMPANYID BIGINT NOT NULL,
  NAME VARCHAR(70) NOT NULL,
  PRODUCTID BIGINT NOT NULL,
  IMAGDEFAULT BOOLEAN DEFAULT FALSE NOT NULL,
  ACTIVE BOOLEAN DEFAULT TRUE NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_REL_PRODUCTIMAGE_COMPANY FOREIGN KEY (COMPANYID) REFERENCES T_COM_COMPANY (ID),
  CONSTRAINT FK_REL_PRODUCTIMAGE_ARTICULO FOREIGN KEY (PRODUCTID) REFERENCES T_BUS_PRODUCT (ID)
);

CREATE TABLE T_BUS_ARTIC2ATRIB (
  ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  COMPANYID BIGINT NOT NULL,
  PRODUCTID BIGINT NOT NULL,
  ATTRIBUTEID BIGINT NOT NULL,
  NOMBRE VARCHAR(20) NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_REL_DESDE_ARTICULO FOREIGN KEY (PRODUCTID) REFERENCES T_BUS_PRODUCT (ID),
  CONSTRAINT FK_REL_HASTA_ATRIBUTO FOREIGN KEY (ATTRIBUTEID) REFERENCES T_BUS_ATRIBUTO (ID)
);

CREATE TABLE T_BUS_INVENTARIO (
  ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  COMPANYID BIGINT NOT NULL,
  PRODUCTID BIGINT NOT NULL,
  STOCK DOUBLE,
  RESERVA DOUBLE,
  FECHA DATE,
  PRIMARY KEY (ID),
  CONSTRAINT FK_REL_INVENTARIO_ARTICULO FOREIGN KEY (PRODUCTID) REFERENCES T_BUS_PRODUCT (ID)
);

CREATE TABLE T_BUS_CURRENCY (
  ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  COMPANYID BIGINT NOT NULL,
  NAME VARCHAR(20) NOT NULL,
  CURBASE BOOLEAN DEFAULT FALSE,
  PRIMARY KEY (ID),
  CONSTRAINT FK_REL_CURRENCY_COMPANY FOREIGN KEY (COMPANYID) REFERENCES T_COM_COMPANY (ID)
);

CREATE TABLE T_BUS_CURRATES (
  ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  COMPANYID BIGINT NOT NULL,
  CURRENCYID BIGINT NOT NULL,
  FROMDATE DATE,
  TODATE DATE,
  RATE DOUBLE,
  PRIMARY KEY (ID),
  CONSTRAINT FK_REL_CURRATES_CURRENCY FOREIGN KEY (CURRENCYID) REFERENCES T_BUS_CURRENCY (ID),
  CONSTRAINT FK_REL_CURRATES_COMPANY FOREIGN KEY (COMPANYID) REFERENCES T_COM_COMPANY (ID)
);

CREATE TABLE T_BUS_PRICELIST (
  ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  PRODUCTID BIGINT NOT NULL,
  CURRENCYID BIGINT NOT NULL,
  VALIDFROM DATE,
  VALIDTO DATE,
  PRICE DOUBLE,
  PRIMARY KEY (ID),
  CONSTRAINT FK_REL_PRICELIST_PRODUCT FOREIGN KEY (PRODUCTID) REFERENCES T_BUS_PRODUCT (ID),
  CONSTRAINT FK_REL_PRICELIST_CURRENCY FOREIGN KEY (CURRENCYID) REFERENCES T_BUS_CURRENCY (ID)
);

CREATE TABLE T_BUS_PRICELISTCOST (
  ID BIGINT NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_REL_COST_PRICELIST FOREIGN KEY (ID) REFERENCES T_BUS_PRICELIST (ID)
);

CREATE TABLE T_BUS_PRICELISTRETAIL (
  ID BIGINT NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_REL_RETAIL_PRICELIST FOREIGN KEY (ID) REFERENCES T_BUS_PRICELIST (ID)
);

/*CREATE TABLE T_BUS_PRICELISTOFERT (
  ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  PRODUCTID BIGINT NOT NULL,
  DESDE DATE,
  HASTA DATE,
  MONTO DOUBLE,
  PRIMARY KEY (ID),
  CONSTRAINT FK_REL_OFERTA_ARTICULO FOREIGN KEY (PRODUCTID) REFERENCES T_BUS_PRODUCT (ID)
);*/

CREATE TABLE T_BUS_CATEG2ARTIC (
  ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  CATEGORYID BIGINT NOT NULL,
  PRODUCTID BIGINT NOT NULL,
  CONSTRAINT FK_REL_CATEGORY_FROM FOREIGN KEY (CATEGORYID) REFERENCES T_BUS_CATEGORY (ID),
  CONSTRAINT FK_REL_ARTICULO_TO FOREIGN KEY (PRODUCTID) REFERENCES T_BUS_PRODUCT (ID)
);

--
-- Table structure for table T_BUS_CLIENT
--

CREATE TABLE T_BUS_CLIENT (
  ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  COMPANYID BIGINT NOT NULL,
  USERID BIGINT NOT NULL,
  NAME VARCHAR(60) NOT NULL,
  LASTNAME VARCHAR(60) NOT NULL,
  LASTNAME2 VARCHAR(60) DEFAULT NULL,
  BIRTHDAY DATE DEFAULT NULL,
  DOCTYPEID BIGINT DEFAULT NULL,
  DOCNUMBER VARCHAR(15) DEFAULT NULL,
  ADDRESS VARCHAR(80) DEFAULT NULL,
  PHONE VARCHAR(10) DEFAULT NULL,
  CELLPHONE VARCHAR(10) DEFAULT NULL,
  EMAIL VARCHAR(30) NOT NULL,
  CITY VARCHAR(20) DEFAULT NULL,
  UBIGEO VARCHAR(6) DEFAULT NULL,
  POSTCODE VARCHAR(6) DEFAULT NULL,
  ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
  PRIMARY KEY (ID),
  CONSTRAINT FK_REL_CLIENT_USER FOREIGN KEY (USERID) REFERENCES T_SEG_USER (ID),
  CONSTRAINT FK_REL_CLIENT_CLIENT FOREIGN KEY (COMPANYID) REFERENCES T_COM_COMPANY (ID),
  CONSTRAINT FK_REL_CLIENT_DOCTYPE FOREIGN KEY (DOCTYPEID) REFERENCES T_BUS_PARAMETER (ID)
);

--
-- Table structure for table T_BUS_PEDIDO_TIPO
--

CREATE TABLE T_BUS_PEDIDO_TIPO (
  TIPOPED_N_CODIGO BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  TIPOPED_V_DESCRIPCION VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (TIPOPED_N_CODIGO)
);

--
-- Table structure for table T_BUS_PEDIDO
--

CREATE TABLE T_BUS_PEDIDO (
  PEDIDO_N_CODIGO BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  COMPANYID BIGINT NOT NULL,
  CLIENTID BIGINT NOT NULL,
  TIPOPED_N_CODIGO BIGINT NOT NULL,
  PEDIDO_D_FECHA DATE DEFAULT NULL,
  PEDIDO_N_IGV INTEGER DEFAULT NULL,
  PEDIDO_N_TOTAL DOUBLE PRECISION DEFAULT NULL,
  PRIMARY KEY (PEDIDO_N_CODIGO),
  CONSTRAINT FK_REL_COMPANY_PEDIDO FOREIGN KEY (COMPANYID) REFERENCES T_COM_COMPANY (ID),
  CONSTRAINT FK_REL_PEDIDO_CLIENTE FOREIGN KEY (CLIENTID) REFERENCES T_BUS_CLIENT (ID),
  CONSTRAINT FK_REL_PEDIDO_TIPO FOREIGN KEY (TIPOPED_N_CODIGO) REFERENCES T_BUS_PEDIDO_TIPO (TIPOPED_N_CODIGO)
);


--
-- Table structure for table T_BUS_PEDIDO2PEDIDO
--

CREATE TABLE T_BUS_PEDIDO2PEDIDO (
  PEDIDO_N_CODIGO_FROM BIGINT NOT NULL,
  PEDIDO_N_CODIGO_TO BIGINT NOT NULL,
  PRIMARY KEY (PEDIDO_N_CODIGO_FROM,PEDIDO_N_CODIGO_TO)
);


--
-- Table structure for table T_BUS_PEDIDO_DET
--

CREATE TABLE T_BUS_PEDIDO_DET (
  PEDIDO_N_CODIGO BIGINT NOT NULL,
  ARTICULO_N_CODIGO BIGINT NOT NULL,
  DETPED_N_CANTIDAD INTEGER DEFAULT NULL,
  PRIMARY KEY (PEDIDO_N_CODIGO,ARTICULO_N_CODIGO),
  CONSTRAINT FK_T_BUS_PEDIDO_DET FOREIGN KEY (PEDIDO_N_CODIGO) REFERENCES T_BUS_PEDIDO (PEDIDO_N_CODIGO),
  CONSTRAINT FK_T_BUS_PEDIDO_DET2 FOREIGN KEY (ARTICULO_N_CODIGO) REFERENCES T_BUS_PRODUCT (ID)
);


--
-- Table structure for table T_BUS_SOLICITUD
--

CREATE TABLE T_BUS_SOLICITUD (
  SOLICITUD_N_CODIGO BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  SOLICITUD_V_RAZON VARCHAR(100) DEFAULT NULL,
  SOLICITUD_N_RUC VARCHAR(11) DEFAULT NULL,
  SOLICITUD_D_FECHA DATE DEFAULT NULL,
  SOLICITUD_N_ESTADO INTEGER DEFAULT NULL,
  SOLICITUD_V_EMAIL VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (SOLICITUD_N_CODIGO)
);


--
-- Table structure for table T_BUS_VENTA_TIPO
--

CREATE TABLE T_BUS_VENTA_TIPO (
  TIPOVEN_N_CODIGO BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  COMPANYID BIGINT NOT NULL,
  TIPOVEN_V_DESCRIPCION VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (TIPOVEN_N_CODIGO),
  CONSTRAINT FK_REL_COMPANY_TIPOVENTA FOREIGN KEY (COMPANYID) REFERENCES T_COM_COMPANY (ID)
);
