--
-- Table structure for table T_COM_COMPANY
--

DROP TABLE IF EXISTS T_COM_COMPANY;
CREATE TABLE T_COM_COMPANY (
  ID BIGINT NOT NULL,
  BUSINESSNAME VARCHAR(200) DEFAULT NULL,
  ACTIVE BIGINT DEFAULT NULL,
  DOCNUMBER VARCHAR(11) DEFAULT NULL,
  DOMAIN VARCHAR(10) DEFAULT NULL,
  PRIMARY KEY (ID)
);


CREATE UNIQUE INDEX T_COM_COMPANY_DOMAIN_UNIQUE ON T_COM_COMPANY(DOMAIN);

--
-- Table structure for table T_COM_AREA
--

DROP TABLE IF EXISTS T_COM_AREA;
CREATE TABLE T_COM_AREA (
  ID BIGINT NOT NULL,
  COMPANYID BIGINT NOT NULL,
  NAME VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_REL_AREA_COMPANY FOREIGN KEY (COMPANYID) REFERENCES T_COM_COMPANY (ID)
);


--
-- Table structure for table T_SEG_ROLE
--

DROP TABLE IF EXISTS T_SEG_ROLE;
CREATE TABLE T_SEG_ROLE (
  ID BIGINT NOT NULL,
  COMPANYID BIGINT NOT NULL,
  AREAID BIGINT NOT NULL,
  NAME VARCHAR(50) DEFAULT NULL,
  DESCRIPTION VARCHAR(300) DEFAULT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_REL_ROLE_COMPANY FOREIGN KEY (COMPANYID) REFERENCES T_COM_COMPANY (ID),
  CONSTRAINT FK_REL_ROLE_AREA FOREIGN KEY (ID) REFERENCES T_COM_AREA (ID)
);


--
-- Table structure for table T_SEG_USER
--

DROP TABLE IF EXISTS T_SEG_USER;
CREATE TABLE T_SEG_USER (
  ID BIGINT NOT NULL,
  COMPANYID BIGINT NOT NULL,
  PASSWORD VARCHAR(150) DEFAULT NULL,
  USERNAME VARCHAR(45) DEFAULT NULL,
  ROLEID BIGINT NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_REL_USER_COMPANY FOREIGN KEY (COMPANYID) REFERENCES T_COM_COMPANY (ID),
  CONSTRAINT FK_REL_USER_ROLE FOREIGN KEY (ROLEID) REFERENCES T_SEG_ROLE (ID)
);


--
-- Table structure for table T_SEG_MODULE
--

DROP TABLE IF EXISTS T_SEG_MODULE;
CREATE TABLE T_SEG_MODULE (
  ID BIGINT NOT NULL,
  COMPANYID BIGINT NOT NULL,
  DESCRIPTION VARCHAR(80) DEFAULT NULL,
  RESOURCE VARCHAR(45) DEFAULT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_REL_COMPANY_MODULE FOREIGN KEY (COMPANYID) REFERENCES T_COM_COMPANY (ID)
);


--
-- Table structure for table T_SEG_ROLE2MODULE
--

DROP TABLE IF EXISTS T_SEG_ROLE2MODULE;
CREATE TABLE T_SEG_ROLE2MODULE (
  ID BIGINT NOT NULL,
  ROLEID BIGINT NOT NULL,
  MODULEID BIGINT NOT NULL,
  ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
  PRIMARY KEY (ID),
  CONSTRAINT FK_T_SEG_ROLE2MODULE FOREIGN KEY (ROLEID) REFERENCES T_SEG_ROLE (ID),
  CONSTRAINT FK_T_SEG_ROLE2MODULE_1 FOREIGN KEY (MODULEID) REFERENCES T_SEG_MODULE (ID) ON DELETE NO ACTION ON UPDATE NO ACTION
);


--
-- Table structure for table T_BUS_PARAMTYPE
--

CREATE TABLE T_BUS_PARAMTYPE (
  ID BIGINT NOT NULL,
  COMPANYID BIGINT NOT NULL,
  NAME VARCHAR(50) NOT NULL,
  DESCRIPTION VARCHAR(150) DEFAULT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_REL_PARAMTYPE_COMPANY FOREIGN KEY (COMPANYID) REFERENCES T_COM_COMPANY (ID)
);


--
-- Table structure for table T_BUS_PARAMETER
--

CREATE TABLE T_BUS_PARAMETER (
  ID BIGINT NOT NULL,
  COMPANYID BIGINT NOT NULL,
  PARAMTYPEID BIGINT NOT NULL,
  NAME VARCHAR(50) NOT NULL,
  DESCRIPTION VARCHAR(150) DEFAULT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_REL_PARAMETER_COMPANY FOREIGN KEY (COMPANYID) REFERENCES T_COM_COMPANY (ID),
  CONSTRAINT FK_REL_PARAMETER_PARAMTYPE FOREIGN KEY (PARAMTYPEID) REFERENCES T_BUS_PARAMTYPE (ID)
);

--
-- Table structure for table T_BUS_UBICACION
--

CREATE TABLE T_BUS_UBICATION (
  ID BIGINT NOT NULL,
  PARENTID BIGINT,
  NAME VARCHAR(60) NOT NULL,
  CODE VARCHAR(6),
  PRIMARY KEY (ID),
  CONSTRAINT FK_REL_UBICACION_PARENTID FOREIGN KEY (PARENTID) REFERENCES T_BUS_UBICACION (ID)
);

--
-- Table structure for table T_BUS_EMPLOYEE
--

DROP TABLE IF EXISTS T_BUS_EMPLOYEE;
CREATE TABLE T_BUS_EMPLOYEE (
  ID BIGINT NOT NULL,
  USERID BIGINT DEFAULT NULL,
  COMPANYID BIGINT NOT NULL,
  NAME VARCHAR(50) NOT NULL,
  LASTNAME VARCHAR(50) NOT NULL,
  LASTNAME2 VARCHAR(50) DEFAULT NULL,
  DOCTYPEID INTEGER NOT NULL,
  DOCNUMBER VARCHAR(15) NOT NULL,
  ADDRESS VARCHAR(70) DEFAULT NULL,
  PHONE VARCHAR(15) DEFAULT NULL,
  CELLPHONE VARCHAR(20) DEFAULT NULL,
  EMAIL VARCHAR(30) NOT NULL,
  CITY VARCHAR(20) DEFAULT NULL,
  UBIGEO VARCHAR(20) DEFAULT NULL,
  DEPARTMENTID INTEGER DEFAULT NULL,
  PROVINCEID INTEGER DEFAULT NULL,
  DISTRICTID INTEGER DEFAULT NULL,
  BIRTHDAY DATE NOT NULL,
  SEXID BIGINT NOT NULL,
  CIVILSTATEID BIGINT,
  ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
  PRIMARY KEY (ID),
  CONSTRAINT FK_REL_EMPLOYEE_USER FOREIGN KEY (USERID) REFERENCES T_SEG_USER (ID),
  CONSTRAINT FK_REL_EMPLOYEE_COMPANY FOREIGN KEY (COMPANYID) REFERENCES T_COM_COMPANY (ID),
  CONSTRAINT FK_REL_EMPLOYEE_DOCTYPE FOREIGN KEY (DOCTYPEID) REFERENCES T_BUS_PARAMETER (ID),
  CONSTRAINT FK_REL_EMPLOYEE_SEX FOREIGN KEY (SEXID) REFERENCES T_BUS_PARAMETER (ID),
  CONSTRAINT FK_REL_EMPLOYEE_CIVILSTATE FOREIGN KEY (CIVILSTATEID) REFERENCES T_BUS_PARAMETER (ID),
  CONSTRAINT FK_REL_EMPLOYEE_DEPARTMENT FOREIGN KEY (DEPARTMENTID) REFERENCES T_BUS_UBICATION (ID),
  CONSTRAINT FK_REL_EMPLOYEE_PROVINCE FOREIGN KEY (PROVINCEID) REFERENCES T_BUS_UBICATION (ID),
  CONSTRAINT FK_REL_EMPLOYEE_DISTRICT FOREIGN KEY (DISTRICTID) REFERENCES T_BUS_UBICATION (ID)
) ;


--
-- Table structure for table T_BUS_CATEGORY
--

DROP TABLE IF EXISTS T_BUS_CATEGORY;
CREATE TABLE T_BUS_CATEGORY (
  ID BIGINT NOT NULL,
  COMPANYID BIGINT NOT NULL,
  NAME VARCHAR(60) DEFAULT NULL,
  ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
  PARENTID BIGINT,
  IMAGE VARCHAR(45) DEFAULT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_REL_CATEGORY_COMPANY FOREIGN KEY (COMPANYID) REFERENCES T_COM_COMPANY (ID),
  CONSTRAINT FK_REL_CATEGORY_CATEGORY FOREIGN KEY (PARENTID) REFERENCES T_BUS_CATEGORY (ID)
);

DROP TABLE IF EXISTS T_BUS_TRADEMARK;
CREATE TABLE T_BUS_TRADEMARK (
  ID BIGINT NOT NULL,
  COMPANYID BIGINT NOT NULL,
  NAME VARCHAR(70) NOT NULL,
  ACTIVE BOOLEAN DEFAULT TRUE NOT NULL,
  IMAGE VARCHAR(45) DEFAULT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_REL_TRADEMARK_COMPANY FOREIGN KEY (COMPANYID) REFERENCES T_COM_COMPANY (ID)
);

--
-- Table structure for table T_BUS_CATEGORY
--

DROP TABLE IF EXISTS T_BUS_ATRIBUTO;
CREATE TABLE T_BUS_ATRIBUTO (
  ID BIGINT NOT NULL,
  NOMBRE VARCHAR(20) NOT NULL,
  DESCR VARCHAR(80),
  ACTIVO INTEGER DEFAULT 1,
  FILTRABLE INTEGER DEFAULT 0,
  --ATR_N_PREDET BIGINT DEFAULT NULL,    --Para el precio por ejemplo, que debe existir si o si.
  CATEGORYID BIGINT,
  PRIMARY KEY (ID),
  CONSTRAINT FK_REL_ATRIBUTO_CATEGORY FOREIGN KEY (CATEGORYID) REFERENCES T_BUS_CATEGORY (ID)
);

--
-- Table structure for table T_BUS_PRODUCT
--

DROP TABLE IF EXISTS T_BUS_PRODUCT;
CREATE TABLE T_BUS_PRODUCT (
  ID BIGINT NOT NULL,
  COMPANYID BIGINT NOT NULL,
  NAME VARCHAR(70) DEFAULT NULL,
  TRADEMARKID BIGINT NOT NULL,
  DESCRIPTION VARCHAR(4000) DEFAULT NULL,
  --ARTICULO_N_PRECIO DECIMAL(8,2) DEFAULT NULL,
  --ARTICULO_N_STOCK BIGINT DEFAULT '0',
  ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
  --IMAGE VARCHAR(45) DEFAULT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_REL_ARTICULO_COMPANY FOREIGN KEY (COMPANYID) REFERENCES T_COM_COMPANY (ID),
  CONSTRAINT FK_REL_ARTICULO_TRADEMARK FOREIGN KEY (TRADEMARKID) REFERENCES T_BUS_TRADEMARK (ID)
);

DROP TABLE IF EXISTS T_BUS_PRODUCTIMAGE;
CREATE TABLE T_BUS_PRODUCTIMAGE (
  ID BIGINT NOT NULL,
  COMPANYID BIGINT NOT NULL,
  NOMBRE VARCHAR(70) NOT NULL,
  PRODUCTID BIGINT NOT NULL,
  IMAGDEFAULT BOOLEAN DEFAULT FALSE NOT NULL,
  ACTIVE BOOLEAN DEFAULT TRUE NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_REL_PRODUCTIMAGE_COMPANY FOREIGN KEY (COMPANYID) REFERENCES T_COM_COMPANY (ID),
  CONSTRAINT FK_REL_PRODUCTIMAGE_ARTICULO FOREIGN KEY (PRODUCTID) REFERENCES T_BUS_PRODUCT (ID)
);


DROP TABLE IF EXISTS T_BUS_ARTIC2ATRIB;
CREATE TABLE T_BUS_ARTIC2ATRIB (
  ID BIGINT NOT NULL,
  COMPANYID BIGINT NOT NULL,
  PRODUCTID BIGINT NOT NULL,
  ATTRIBUTEID BIGINT NOT NULL,
  NOMBRE VARCHAR(20) NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_REL_DESDE_ARTICULO FOREIGN KEY (PRODUCTID) REFERENCES T_BUS_PRODUCT (ID),
  CONSTRAINT FK_REL_HASTA_ATRIBUTO FOREIGN KEY (ATTRIBUTEID) REFERENCES T_BUS_ATRIBUTO (ID)
);


DROP TABLE IF EXISTS T_BUS_INVENTARIO;
CREATE TABLE T_BUS_INVENTARIO (
  ID BIGINT NOT NULL,
  COMPANYID BIGINT NOT NULL,
  PRODUCTID BIGINT NOT NULL,
  STOCK DECIMAL(8,2),
  RESERVA DECIMAL(8,2),
  FECHA DATE,
  PRIMARY KEY (ID),
  CONSTRAINT FK_REL_INVENTARIO_ARTICULO FOREIGN KEY (PRODUCTID) REFERENCES T_BUS_PRODUCT (ID),
  CONSTRAINT FK_REL_INVENTARIO_COMPANY FOREIGN KEY (COMPANYID) REFERENCES T_COM_COMPANY (ID)
);

DROP TABLE IF EXISTS T_BUS_CURRENCY;
CREATE TABLE T_BUS_CURRENCY (
  ID BIGINT NOT NULL,
  NAME VARCHAR(20) NOT NULL,
  CURBASE BOOLEAN DEFAULT FALSE,
  PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS T_BUS_CURRATES;
CREATE TABLE T_BUS_CURRATES (
  ID BIGINT NOT NULL,
  CURRENCYID BIGINT NOT NULL,
  FROMDATE DATE,
  TODATE DATE,
  AMOUNT DECIMAL(12,4),
  PRIMARY KEY (ID),
  CONSTRAINT FK_REL_CURRATES_CURRENCY FOREIGN KEY (CURRENCYID) REFERENCES T_BUS_CURRENCY (ID)
);

DROP TABLE IF EXISTS T_BUS_PRECIO;
CREATE TABLE T_BUS_PRECIO (
  ID BIGINT NOT NULL,
  PRODUCTID BIGINT NOT NULL,
  DESDE DATE,
  HASTA DATE,
  MONTO DECIMAL(14,4),
  PRIMARY KEY (ID),
  CONSTRAINT FK_REL_PRECIO_ARTICULO FOREIGN KEY (PRODUCTID) REFERENCES T_BUS_PRODUCT (ID)
);


DROP TABLE IF EXISTS T_BUS_COSTO;
CREATE TABLE T_BUS_COSTO (
  ID BIGINT NOT NULL,
  PRODUCTID BIGINT NOT NULL,
  DESDE DATE,
  HASTA DATE,
  MONTO DECIMAL(14,4),
  PRIMARY KEY (ID),
  CONSTRAINT FK_REL_COSTO_ARTICULO FOREIGN KEY (PRODUCTID) REFERENCES T_BUS_PRODUCT (ID)
);


DROP TABLE IF EXISTS T_BUS_OFERTA;
CREATE TABLE T_BUS_OFERTA (
  ID BIGINT NOT NULL,
  PRODUCTID BIGINT NOT NULL,
  DESDE DATE,
  HASTA DATE,
  MONTO DECIMAL(14,4),
  PRIMARY KEY (ID),
  CONSTRAINT FK_REL_OFERTA_ARTICULO FOREIGN KEY (PRODUCTID) REFERENCES T_BUS_PRODUCT (ID)
);


DROP TABLE IF EXISTS T_BUS_CATEG2ARTIC;
CREATE TABLE T_BUS_CATEG2ARTIC (
  ID BIGINT NOT NULL,
  CATEGORYID BIGINT NOT NULL,
  PRODUCTID BIGINT NOT NULL,
  CONSTRAINT FK_REL_CATEGORY_FROM FOREIGN KEY (CATEGORYID) REFERENCES T_BUS_CATEGORY (ID),
  CONSTRAINT FK_REL_ARTICULO_TO FOREIGN KEY (PRODUCTID) REFERENCES T_BUS_PRODUCT (ID)
);


--
-- Table structure for table T_BUS_CLIENT
--

DROP TABLE IF EXISTS T_BUS_CLIENT;
CREATE TABLE T_BUS_CLIENT (
  ID BIGINT NOT NULL,
  COMPANYID BIGINT NOT NULL,
  USERID BIGINT NOT NULL,
  NAME VARCHAR(60) NOT NULL,
  LASTNAME VARCHAR(60) NOT NULL,
  LASTNAME2 VARCHAR(60) DEFAULT NULL,
  BIRTHDAY DATE DEFAULT NULL,
  DOCTYPEID BIGINT DEFAULT NULL,
  DOCNUMBER VARCHAR(15) DEFAULT NULL,
  ADDRESS VARCHAR(80) DEFAULT NULL,
  PHONE VARCHAR(10) DEFAULT NULL,
  CELLPHONE VARCHAR(10) DEFAULT NULL,
  EMAIL VARCHAR(30) NOT NULL,
  CITY VARCHAR(20) DEFAULT NULL,
  UBIGEO VARCHAR(6) DEFAULT NULL,
  POSTCODE VARCHAR(6) DEFAULT NULL,
  ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
  PRIMARY KEY (ID),
  CONSTRAINT FK_REL_CLIENT_USER FOREIGN KEY (USERID) REFERENCES T_SEG_USER (ID),
  CONSTRAINT FK_REL_CLIENT_COMPANY FOREIGN KEY (COMPANYID) REFERENCES T_COM_COMPANY (ID),
  CONSTRAINT FK_REL_CLIENT_DOCTYPE FOREIGN KEY (DOCTYPEID) REFERENCES T_BUS_PARAMETER (ID)
);

--
-- Table structure for table T_BUS_PEDIDO_TIPO
--

DROP TABLE IF EXISTS T_BUS_PEDIDO_TIPO;
CREATE TABLE T_BUS_PEDIDO_TIPO (
  TIPOPED_N_CODIGO BIGINT NOT NULL,
  TIPOPED_V_DESCRIPCION VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (TIPOPED_N_CODIGO)
);

--
-- Table structure for table T_BUS_PEDIDO
--

DROP TABLE IF EXISTS T_BUS_PEDIDO;
CREATE TABLE T_BUS_PEDIDO (
  PEDIDO_N_CODIGO BIGINT NOT NULL,
  COMPANYID BIGINT NOT NULL,
  CLIENTID BIGINT NOT NULL,
  TIPOPED_N_CODIGO BIGINT NOT NULL,
  PEDIDO_D_FECHA DATE DEFAULT NULL,
  PEDIDO_N_IGV BIGINT DEFAULT NULL,
  PEDIDO_N_TOTAL DECIMAL(8,2) DEFAULT NULL,
  PRIMARY KEY (PEDIDO_N_CODIGO),
  CONSTRAINT FK_REL_COMPANY_PEDIDO FOREIGN KEY (COMPANYID) REFERENCES T_COM_COMPANY (ID),
  CONSTRAINT FK_REL_PEDIDO_CLIENTE FOREIGN KEY (CLIENTID) REFERENCES T_BUS_CLIENT (ID),
  CONSTRAINT FK_REL_PEDIDO_TIPO FOREIGN KEY (TIPOPED_N_CODIGO) REFERENCES T_BUS_PEDIDO_TIPO (TIPOPED_N_CODIGO)
);


--
-- Table structure for table T_BUS_PEDIDO2PEDIDO
--

DROP TABLE IF EXISTS T_BUS_PEDIDO2PEDIDO;
CREATE TABLE T_BUS_PEDIDO2PEDIDO (
  PEDIDO_N_CODIGO_FROM BIGINT NOT NULL,
  PEDIDO_N_CODIGO_TO BIGINT NOT NULL,
  PRIMARY KEY (PEDIDO_N_CODIGO_FROM,PEDIDO_N_CODIGO_TO)
);


--
-- Table structure for table T_BUS_PEDIDO_DET
--

DROP TABLE IF EXISTS T_BUS_PEDIDO_DET;
CREATE TABLE T_BUS_PEDIDO_DET (
  PEDIDO_N_CODIGO BIGINT NOT NULL,
  ARTICULO_N_CODIGO BIGINT NOT NULL,
  DETPED_N_CANTIDAD BIGINT DEFAULT NULL,
  PRIMARY KEY (PEDIDO_N_CODIGO,ARTICULO_N_CODIGO),
  CONSTRAINT FK_T_BUS_PEDIDO_DET FOREIGN KEY (PEDIDO_N_CODIGO) REFERENCES T_BUS_PEDIDO (PEDIDO_N_CODIGO),
  CONSTRAINT FK_T_BUS_PEDIDO_DET2 FOREIGN KEY (ARTICULO_N_CODIGO) REFERENCES T_BUS_PRODUCT (ID)
);


--
-- Table structure for table T_BUS_SOLICITUD
--

DROP TABLE IF EXISTS T_BUS_SOLICITUD;
CREATE TABLE T_BUS_SOLICITUD (
  SOLICITUD_N_CODIGO BIGINT NOT NULL,
  SOLICITUD_V_RAZON VARCHAR(100) DEFAULT NULL,
  SOLICITUD_N_RUC VARCHAR(11) DEFAULT NULL,
  SOLICITUD_D_FECHA DATE DEFAULT NULL,
  SOLICITUD_N_ESTADO INTEGER DEFAULT NULL,
  SOLICITUD_V_EMAIL VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (SOLICITUD_N_CODIGO)
);


--
-- Table structure for table T_BUS_VENTA_TIPO
--

DROP TABLE IF EXISTS T_BUS_VENTA_TIPO;
CREATE TABLE T_BUS_VENTA_TIPO (
  TIPOVEN_N_CODIGO BIGINT NOT NULL,
  COMPANYID BIGINT NOT NULL,
  TIPOVEN_V_DESCRIPCION VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (TIPOVEN_N_CODIGO),
  CONSTRAINT FK_REL_COMPANY_TIPOVENTA FOREIGN KEY (COMPANYID) REFERENCES T_COM_COMPANY (ID)
);

CREATE SEQUENCE T_COM_AREA_ID_SEQ;
ALTER TABLE T_COM_AREA ALTER COLUMN ID SET DEFAULT nextval('T_COM_AREA_ID_SEQ');
ALTER SEQUENCE T_COM_AREA_ID_SEQ OWNED BY T_COM_AREA.ID;

CREATE SEQUENCE T_BUS_PARAMTYPE_ID_SEQ;
ALTER TABLE T_BUS_PARAMTYPE ALTER COLUMN ID SET DEFAULT nextval('T_BUS_PARAMTYPE_ID_SEQ');
ALTER SEQUENCE T_BUS_PARAMTYPE_ID_SEQ OWNED BY T_BUS_PARAMTYPE.ID;

CREATE SEQUENCE T_BUS_PARAMETER_ID_SEQ;
ALTER TABLE T_BUS_PARAMETER ALTER COLUMN ID SET DEFAULT nextval('T_BUS_PARAMETER_ID_SEQ');
ALTER SEQUENCE T_BUS_PARAMETER_ID_SEQ OWNED BY T_BUS_PARAMETER.ID;

CREATE SEQUENCE T_BUS_UBICACION_ID_SEQ START WITH 2057;
ALTER TABLE T_BUS_UBICACION ALTER COLUMN ID SET DEFAULT nextval('T_BUS_UBICACION_ID_SEQ');
ALTER SEQUENCE T_BUS_UBICACION_ID_SEQ OWNED BY T_BUS_UBICACION.ID;

CREATE SEQUENCE T_BUS_EMPLOYEE_ID_SEQ;
ALTER TABLE T_BUS_EMPLOYEE ALTER COLUMN ID SET DEFAULT nextval('T_BUS_EMPLOYEE_ID_SEQ');
ALTER SEQUENCE T_BUS_EMPLOYEE_ID_SEQ OWNED BY T_BUS_EMPLOYEE.ID;

CREATE SEQUENCE T_COM_COMPANY_ID_SEQ;
ALTER TABLE T_COM_COMPANY ALTER COLUMN ID SET DEFAULT nextval('T_COM_COMPANY_ID_SEQ');
ALTER SEQUENCE T_COM_COMPANY_ID_SEQ OWNED BY T_COM_COMPANY.ID;

CREATE SEQUENCE T_BUS_TRADEMARK_ID_SEQ;
ALTER TABLE T_BUS_TRADEMARK ALTER COLUMN ID SET DEFAULT nextval('T_BUS_TRADEMARK_ID_SEQ');
ALTER SEQUENCE T_BUS_TRADEMARK_ID_SEQ OWNED BY T_BUS_TRADEMARK.ID;

CREATE SEQUENCE T_BUS_PRODUCTIMAGE_ID_SEQ;
ALTER TABLE T_BUS_PRODUCTIMAGE ALTER COLUMN ID SET DEFAULT nextval('T_BUS_PRODUCTIMAGE_ID_SEQ');
ALTER SEQUENCE T_BUS_PRODUCTIMAGE_ID_SEQ OWNED BY T_BUS_PRODUCTIMAGE.ID;

CREATE SEQUENCE T_BUS_PRODUCT_ID_SEQ;
ALTER TABLE T_BUS_PRODUCT ALTER COLUMN ID SET DEFAULT nextval('T_BUS_PRODUCT_ID_SEQ');
ALTER SEQUENCE T_BUS_PRODUCT_ID_SEQ OWNED BY T_BUS_PRODUCT.ID;

CREATE SEQUENCE T_BUS_ARTIC2ATRIB_ID_SEQ;
ALTER TABLE T_BUS_ARTIC2ATRIB ALTER COLUMN ID SET DEFAULT nextval('T_BUS_ARTIC2ATRIB_ID_SEQ');
ALTER SEQUENCE T_BUS_ARTIC2ATRIB_ID_SEQ OWNED BY T_BUS_ARTIC2ATRIB.ID;

CREATE SEQUENCE T_BUS_CATEGORY_ID_SEQ;
ALTER TABLE T_BUS_CATEGORY ALTER COLUMN ID SET DEFAULT nextval('T_BUS_CATEGORY_ID_SEQ');
ALTER SEQUENCE T_BUS_CATEGORY_ID_SEQ OWNED BY T_BUS_CATEGORY.ID;

CREATE SEQUENCE T_BUS_CATEG2ARTIC_ID_SEQ;
ALTER TABLE T_BUS_CATEG2ARTIC ALTER COLUMN ID SET DEFAULT nextval('T_BUS_CATEG2ARTIC_ID_SEQ');
ALTER SEQUENCE T_BUS_CATEG2ARTIC_ID_SEQ OWNED BY T_BUS_CATEG2ARTIC.ID;

CREATE SEQUENCE T_BUS_ATRIBUTO_ID_SEQ;
ALTER TABLE T_BUS_ATRIBUTO ALTER COLUMN ID SET DEFAULT nextval('T_BUS_ATRIBUTO_ID_SEQ');
ALTER SEQUENCE T_BUS_ATRIBUTO_ID_SEQ OWNED BY T_BUS_ATRIBUTO.ID;

CREATE SEQUENCE T_BUS_INVENTARIO_ID_SEQ;
ALTER TABLE T_BUS_INVENTARIO ALTER COLUMN ID SET DEFAULT nextval('T_BUS_INVENTARIO_ID_SEQ');
ALTER SEQUENCE T_BUS_INVENTARIO_ID_SEQ OWNED BY T_BUS_INVENTARIO.ID;

CREATE SEQUENCE T_BUS_CURRENCY_ID_SEQ;
ALTER TABLE T_BUS_CURRENCY ALTER COLUMN ID SET DEFAULT nextval('T_BUS_CURRENCY_ID_SEQ');
ALTER SEQUENCE T_BUS_CURRENCY_ID_SEQ OWNED BY T_BUS_CURRENCY.ID;

CREATE SEQUENCE T_BUS_CURRATES_ID_SEQ;
ALTER TABLE T_BUS_CURRATES ALTER COLUMN ID SET DEFAULT nextval('T_BUS_CURRATES_ID_SEQ');
ALTER SEQUENCE T_BUS_CURRATES_ID_SEQ OWNED BY T_BUS_CURRATES.ID;

CREATE SEQUENCE T_BUS_PRECIO_ID_SEQ;
ALTER TABLE T_BUS_PRECIO ALTER COLUMN ID SET DEFAULT nextval('T_BUS_PRECIO_ID_SEQ');
ALTER SEQUENCE T_BUS_PRECIO_ID_SEQ OWNED BY T_BUS_PRECIO.ID;

CREATE SEQUENCE T_BUS_COSTO_ID_SEQ;
ALTER TABLE T_BUS_COSTO ALTER COLUMN ID SET DEFAULT nextval('T_BUS_COSTO_ID_SEQ');
ALTER SEQUENCE T_BUS_COSTO_ID_SEQ OWNED BY T_BUS_COSTO.ID;

CREATE SEQUENCE T_BUS_OFERTA_ID_SEQ;
ALTER TABLE T_BUS_OFERTA ALTER COLUMN ID SET DEFAULT nextval('T_BUS_OFERTA_ID_SEQ');
ALTER SEQUENCE T_BUS_OFERTA_ID_SEQ OWNED BY T_BUS_OFERTA.ID;

CREATE SEQUENCE T_BUS_CLIENT_ID_SEQ;
ALTER TABLE T_BUS_CLIENT ALTER COLUMN ID SET DEFAULT nextval('T_BUS_CLIENT_ID_SEQ');
ALTER SEQUENCE T_BUS_CLIENT_ID_SEQ OWNED BY T_BUS_CLIENT.ID;

CREATE SEQUENCE T_BUS_PEDIDO_ID_SEQ;
ALTER TABLE T_BUS_PEDIDO ALTER COLUMN PEDIDO_N_CODIGO SET DEFAULT nextval('T_BUS_PEDIDO_ID_SEQ');
ALTER SEQUENCE T_BUS_PEDIDO_ID_SEQ OWNED BY T_BUS_PEDIDO.PEDIDO_N_CODIGO;

CREATE SEQUENCE T_BUS_PEDIDO_TIPO_ID_SEQ;
ALTER TABLE T_BUS_PEDIDO_TIPO ALTER COLUMN TIPOPED_N_CODIGO SET DEFAULT nextval('T_BUS_PEDIDO_TIPO_ID_SEQ');
ALTER SEQUENCE T_BUS_PEDIDO_TIPO_ID_SEQ OWNED BY T_BUS_PEDIDO_TIPO.TIPOPED_N_CODIGO;

CREATE SEQUENCE T_BUS_SOLICITUD_ID_SEQ;
ALTER TABLE T_BUS_SOLICITUD ALTER COLUMN SOLICITUD_N_CODIGO SET DEFAULT nextval('T_BUS_SOLICITUD_ID_SEQ');
ALTER SEQUENCE T_BUS_SOLICITUD_ID_SEQ OWNED BY T_BUS_SOLICITUD.SOLICITUD_N_CODIGO;

CREATE SEQUENCE T_SEG_MODULE_ID_SEQ;
ALTER TABLE T_SEG_MODULE ALTER COLUMN ID SET DEFAULT nextval('T_SEG_MODULE_ID_SEQ');
ALTER SEQUENCE T_SEG_MODULE_ID_SEQ OWNED BY T_SEG_MODULE.ID;

CREATE SEQUENCE T_SEG_ROLE_ID_SEQ;
ALTER TABLE T_SEG_ROLE ALTER COLUMN ID SET DEFAULT nextval('T_SEG_ROLE_ID_SEQ');
ALTER SEQUENCE T_SEG_ROLE_ID_SEQ OWNED BY T_SEG_ROLE.ID;

CREATE SEQUENCE T_SEG_ROLE2MODULE_ID_SEQ;
ALTER TABLE T_SEG_ROLE2MODULE ALTER COLUMN ID SET DEFAULT nextval('T_SEG_ROLE2MODULE_ID_SEQ');
ALTER SEQUENCE T_SEG_ROLE2MODULE_ID_SEQ OWNED BY T_SEG_ROLE2MODULE.ID;

CREATE SEQUENCE T_SEG_USER_ID_SEQ;
ALTER TABLE T_SEG_USER ALTER COLUMN ID SET DEFAULT nextval('T_SEG_USER_ID_SEQ');
ALTER SEQUENCE T_SEG_USER_ID_SEQ OWNED BY T_SEG_USER.ID;

-- Dump completed on 2011-01-06  5:11:20
