--
-- Table structure for table T_EMP_EMPRESA
--

CREATE TABLE T_EMP_EMPRESA (
  EMPRESA_N_CODIGO INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  EMPRESA_V_RAZONSOCIAL varchar(200) DEFAULT NULL,
  EMPRESA_N_ACTIVO INTEGER DEFAULT NULL,
  EMPRESA_V_RUC varchar(11) DEFAULT NULL,
  EMPRESA_V_DOMINIO varchar(10) DEFAULT NULL,
  PRIMARY KEY (EMPRESA_N_CODIGO)
);


CREATE UNIQUE INDEX EMPRESA_V_DOMINIO_UNIQUE ON T_EMP_EMPRESA(EMPRESA_V_DOMINIO);

--
-- Table structure for table T_EMP_AREA
--

CREATE TABLE T_EMP_AREA (
  AREA_N_CODIGO INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  EMPRESA_N_CODIGO INTEGER NOT NULL,
  AREA_V_NOMBRE varchar(50) DEFAULT NULL,
  PRIMARY KEY (AREA_N_CODIGO),
  CONSTRAINT FK_REL_EMPRESA_AREA FOREIGN KEY (EMPRESA_N_CODIGO) REFERENCES T_EMP_EMPRESA (EMPRESA_N_CODIGO)
);


--
-- Table structure for table T_SEG_PERFIL
--

CREATE TABLE T_SEG_PERFIL (
  PERFIL_N_CODIGO INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  EMPRESA_N_CODIGO INTEGER NOT NULL,
  AREA_N_CODIGO INTEGER NOT NULL,
  PERFIL_V_FUNCION varchar(50) DEFAULT NULL,
  PERFIL_V_DESCRIPCION varchar(300) DEFAULT NULL,
  PRIMARY KEY (PERFIL_N_CODIGO),
  CONSTRAINT FK_REL_EMPRESA_PERFIL FOREIGN KEY (EMPRESA_N_CODIGO) REFERENCES T_EMP_EMPRESA (EMPRESA_N_CODIGO),
  CONSTRAINT FK_REL_PERFIL_AREA FOREIGN KEY (AREA_N_CODIGO) REFERENCES T_EMP_AREA (AREA_N_CODIGO)
);


--
-- Table structure for table T_SEG_USUARIO
--

CREATE TABLE T_SEG_USUARIO (
  USUARIO_N_CODIGO INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  EMPRESA_N_CODIGO INTEGER NOT NULL,
  USUARIO_V_CONTRASENA varchar(150) DEFAULT NULL,
  USUARIO_V_USERNAME varchar(45) DEFAULT NULL,
  PRIMARY KEY (USUARIO_N_CODIGO),
  CONSTRAINT FK_REL_EMPRESA_USUARIO FOREIGN KEY (EMPRESA_N_CODIGO) REFERENCES T_EMP_EMPRESA (EMPRESA_N_CODIGO)
);


--
-- Table structure for table T_SEG_MODULO
--

CREATE TABLE T_SEG_MODULO (
  MODULO_N_CODIGO INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  EMPRESA_N_CODIGO INTEGER NOT NULL,
  MODULO_V_DESC varchar(50) DEFAULT NULL,
  MODULO_V_RECURSO varchar(45) DEFAULT NULL,
  PRIMARY KEY (MODULO_N_CODIGO),
  CONSTRAINT FK_REL_EMPRESA_MODULO FOREIGN KEY (EMPRESA_N_CODIGO) REFERENCES T_EMP_EMPRESA (EMPRESA_N_CODIGO)
);


--
-- Table structure for table T_SEG_MOD_DET
--

CREATE TABLE T_SEG_MOD_DET (
  PERFIL_N_CODIGO INTEGER NOT NULL,
  MODULO_N_CODIGO INTEGER NOT NULL,
  MODDET_N_HABILITADO INTEGER DEFAULT NULL,
  PRIMARY KEY (PERFIL_N_CODIGO,MODULO_N_CODIGO),
  CONSTRAINT FK_T_SEG_MOD_DET FOREIGN KEY (PERFIL_N_CODIGO) REFERENCES T_SEG_PERFIL (PERFIL_N_CODIGO),
  CONSTRAINT FK_T_SEG_MOD_DET_1 FOREIGN KEY (MODULO_N_CODIGO) REFERENCES T_SEG_MODULO (MODULO_N_CODIGO) ON DELETE NO ACTION ON UPDATE NO ACTION
);


--
-- Table structure for table T_EMP_EMPLEADO
--

CREATE TABLE T_EMP_EMPLEADO (
  EMPLEADO_N_CODIGO INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  PERFIL_N_CODIGO INTEGER NOT NULL,
  USUARIO_N_CODIGO INTEGER NOT NULL,
  EMPRESA_N_CODIGO INTEGER NOT NULL,
  EMPLEADO_V_NOMBRE varchar(50) DEFAULT NULL,
  EMPLEADO_V_APELLIDO varchar(50) DEFAULT NULL,
  EMPLEADO_V_DNI varchar(15) DEFAULT NULL,
  EMPLEADO_V_DIRECCION varchar(70) DEFAULT NULL,
  EMPLEADO_V_TELEFONO varchar(15) DEFAULT NULL,
  EMPLEADO_V_CELULAR varchar(20) DEFAULT NULL,
  EMPLEADO_V_EMAIL varchar(30) DEFAULT NULL,
  EMPLEADO_V_CIUDAD varchar(20) DEFAULT NULL,
  EMPLEADO_V_REGION varchar(20) DEFAULT NULL,
  EMPLEADO_D_FECHNAC date DEFAULT NULL,
  EMPLEADO_N_ACTIVO INTEGER DEFAULT NULL,
  PRIMARY KEY (EMPLEADO_N_CODIGO),
  CONSTRAINT FK_REL_EMPLEADO_PERFIL FOREIGN KEY (PERFIL_N_CODIGO) REFERENCES T_SEG_PERFIL (PERFIL_N_CODIGO),
  CONSTRAINT FK_REL_EMPLEADO_USUARIO FOREIGN KEY (USUARIO_N_CODIGO) REFERENCES T_SEG_USUARIO (USUARIO_N_CODIGO),
  CONSTRAINT FK_REL_EMPRESA_EMPLEADO FOREIGN KEY (EMPRESA_N_CODIGO) REFERENCES T_EMP_EMPRESA (EMPRESA_N_CODIGO)
) ;


--
-- Table structure for table T_NEG_CATEGORIA
--

CREATE TABLE T_NEG_CATEGORIA (
  CATEGORIA_N_CODIGO INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  EMPRESA_N_CODIGO INTEGER NOT NULL,
  CATEGORIA_V_NOMBRE varchar(60) DEFAULT NULL,
  CATEGORIA_N_CODIGO_P INTEGER,
  PRIMARY KEY (CATEGORIA_N_CODIGO),
  CONSTRAINT FK_REL_CATEGORIA_EMPRESA FOREIGN KEY (EMPRESA_N_CODIGO) REFERENCES T_EMP_EMPRESA (EMPRESA_N_CODIGO),
  CONSTRAINT FK_REL_CATEGORIA_CATEGORIA FOREIGN KEY (CATEGORIA_N_CODIGO_P) REFERENCES T_NEG_CATEGORIA (CATEGORIA_N_CODIGO)
);

CREATE TABLE T_NEG_ATRIBUTO (
  ATR_N_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  ATR_V_NOMBRE VARCHAR(20) NOT NULL,
  ATR_V_DESCR VARCHAR(80),
  ATR_N_ACTIVO INTEGER DEFAULT 1,
  ATR_N_FILTRABLE INTEGER DEFAULT 0,
  --ATR_N_PREDET INTEGER DEFAULT NULL,    --Para el precio por ejemplo, que debe existir si o si.
  CATEG_N_CODIGO INTEGER,
  PRIMARY KEY (ATR_N_ID),
  CONSTRAINT FK_REL_ATRIBUTO_CATEGORIA FOREIGN KEY (CATEG_N_CODIGO) REFERENCES T_NEG_CATEGORIA (CATEGORIA_N_CODIGO)
  
);

--
-- Table structure for table T_NEG_ARTICULO
--

CREATE TABLE T_NEG_ARTICULO (
  ARTICULO_N_CODIGO INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  EMPRESA_N_CODIGO INTEGER NOT NULL,
  --CATEGORIA_N_CODIGO INTEGER NOT NULL,
  ARTICULO_V_NOMBRE varchar(70) DEFAULT NULL,
  --ARTICULO_V_MARCA varchar(30) DEFAULT NULL,
  ARTICULO_V_DESCRIPCION varchar(4000) DEFAULT NULL,
  --ARTICULO_N_PRECIO DOUBLE PRECISION DEFAULT NULL,
  --ARTICULO_N_STOCK INTEGER DEFAULT 0,
  ARTICULO_N_ACTIVO INTEGER DEFAULT NULL,
  ARTICULO_V_IMAGEN varchar(45) DEFAULT NULL,
  PRIMARY KEY (ARTICULO_N_CODIGO),
  --CONSTRAINT FK_REL_ARTICULO_CATEG FOREIGN KEY (CATEGORIA_N_CODIGO) REFERENCES T_NEG_CATEGORIA (CATEGORIA_N_CODIGO),
  CONSTRAINT FK_REL_EMPRESA_ARTICULO FOREIGN KEY (EMPRESA_N_CODIGO) REFERENCES T_EMP_EMPRESA (EMPRESA_N_CODIGO)
);

CREATE TABLE T_NEG_ARTIC2ATRIB (
  ARTI_N_ID INTEGER NOT NULL,
  ATRI_N_ID INTEGER NOT NULL,
  ARTI2ATRI_V_NOMBRE VARCHAR(20) NOT NULL,
  CONSTRAINT FK_REL_DESDE_ARTICULO FOREIGN KEY (ARTI_N_ID) REFERENCES T_NEG_ARTICULO (ARTICULO_N_CODIGO),
  CONSTRAINT FK_REL_HASTA_ATRIBUTO FOREIGN KEY (ATRI_N_ID) REFERENCES T_NEG_ATRIBUTO (ATR_N_ID)
);

CREATE TABLE T_NEG_INVENTARIO (
  INVE_N_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  ARTI_N_ID INTEGER NOT NULL,
  INVE_D_STOCK DOUBLE,
  INVE_D_RESERVA DOUBLE,
  INVE_F_FECHA DATE,
  PRIMARY KEY (INVE_N_ID),
  CONSTRAINT FK_REL_INVENTARIO_ARTICULO FOREIGN KEY (ARTI_N_ID) REFERENCES T_NEG_ARTICULO (ARTICULO_N_CODIGO)
);

CREATE TABLE T_NEG_PRECIO (
  PREC_N_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  ARTI_N_ID INTEGER NOT NULL,
  PREC_F_DESDE DATE,
  PREC_F_HASTA DATE,
  PREC_D_MONTO DOUBLE,
  PRIMARY KEY (PREC_N_ID),
  CONSTRAINT FK_REL_PRECIO_ARTICULO FOREIGN KEY (ARTI_N_ID) REFERENCES T_NEG_ARTICULO (ARTICULO_N_CODIGO)
);

CREATE TABLE T_NEG_COSTO (
  COST_N_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  ARTI_N_ID INTEGER NOT NULL,
  COST_F_DESDE DATE,
  COST_F_HASTA DATE,
  COST_D_MONTO DOUBLE,
  PRIMARY KEY (COST_N_ID),
  CONSTRAINT FK_REL_COSTO_ARTICULO FOREIGN KEY (ARTI_N_ID) REFERENCES T_NEG_ARTICULO (ARTICULO_N_CODIGO)
);

CREATE TABLE T_NEG_OFERTA (
  OFER_N_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  ARTI_N_ID INTEGER NOT NULL,
  OFER_F_DESDE DATE,
  OFER_F_HASTA DATE,
  OFER_D_MONTO DOUBLE,
  PRIMARY KEY (OFER_N_ID),
  CONSTRAINT FK_REL_OFERTA_ARTICULO FOREIGN KEY (ARTI_N_ID) REFERENCES T_NEG_ARTICULO (ARTICULO_N_CODIGO)
);

CREATE TABLE T_NEG_CATEG2ARTIC (
  CATE_N_ID INTEGER NOT NULL,
  ARTI_N_ID INTEGER NOT NULL,
  CONSTRAINT FK_REL_CATEGORIA_FROM FOREIGN KEY (CATE_N_ID) REFERENCES T_NEG_CATEGORIA (CATEGORIA_N_CODIGO),
  CONSTRAINT FK_REL_ARTICULO_TO FOREIGN KEY (ARTI_N_ID) REFERENCES T_NEG_ARTICULO (ARTICULO_N_CODIGO)
);

--
-- Table structure for table T_NEG_CLIENTE
--

CREATE TABLE T_NEG_CLIENTE (
  CLIENTE_N_CODIGO INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  EMPRESA_N_CODIGO INTEGER NOT NULL,
  USUARIO_N_CODIGO INTEGER NOT NULL,
  CLIENTE_V_NOMBRE varchar(60) DEFAULT NULL,
  CLIENTE_V_APELLIDO varchar(60) DEFAULT NULL,
  CLIENTE_D_FECHANAC date DEFAULT NULL,
  CLIENTE_N_DNI INTEGER DEFAULT NULL,
  CLIENTE_V_DIRECCION varchar(80) DEFAULT NULL,
  CLIENTE_V_TELEFONO varchar(10) DEFAULT NULL,
  CLIENTE_V_CELULAR varchar(10) DEFAULT NULL,
  CLIENTE_V_EMAIL varchar(30) DEFAULT NULL,
  CLIENTE_V_CIUDAD varchar(20) DEFAULT NULL,
  CLIENTE_V_REGION varchar(20) DEFAULT NULL,
  CLIENTE_V_CODPOSTAL INTEGER DEFAULT NULL,
  CLIENTE_N_ACTIVO INTEGER DEFAULT NULL,
  PRIMARY KEY (CLIENTE_N_CODIGO),
  CONSTRAINT FK_REL_CLIENTE_USUARIO FOREIGN KEY (USUARIO_N_CODIGO) REFERENCES T_SEG_USUARIO (USUARIO_N_CODIGO),
  CONSTRAINT FK_REL_EMPRESA_CLIENTE FOREIGN KEY (EMPRESA_N_CODIGO) REFERENCES T_EMP_EMPRESA (EMPRESA_N_CODIGO)
);

--
-- Table structure for table T_NEG_PEDIDO_TIPO
--

CREATE TABLE T_NEG_PEDIDO_TIPO (
  TIPOPED_N_CODIGO INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  TIPOPED_V_DESCRIPCION varchar(50) DEFAULT NULL,
  PRIMARY KEY (TIPOPED_N_CODIGO)
);

--
-- Table structure for table T_NEG_PEDIDO
--

CREATE TABLE T_NEG_PEDIDO (
  PEDIDO_N_CODIGO INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  EMPRESA_N_CODIGO INTEGER NOT NULL,
  CLIENTE_N_CODIGO INTEGER NOT NULL,
  TIPOPED_N_CODIGO INTEGER NOT NULL,
  PEDIDO_D_FECHA date DEFAULT NULL,
  PEDIDO_N_IGV INTEGER DEFAULT NULL,
  PEDIDO_N_TOTAL DOUBLE PRECISION DEFAULT NULL,
  PRIMARY KEY (PEDIDO_N_CODIGO),
  CONSTRAINT FK_REL_EMPRESA_PEDIDO FOREIGN KEY (EMPRESA_N_CODIGO) REFERENCES T_EMP_EMPRESA (EMPRESA_N_CODIGO),
  CONSTRAINT FK_REL_PEDIDO_CLIENTE FOREIGN KEY (CLIENTE_N_CODIGO) REFERENCES T_NEG_CLIENTE (CLIENTE_N_CODIGO),
  CONSTRAINT FK_REL_PEDIDO_TIPO FOREIGN KEY (TIPOPED_N_CODIGO) REFERENCES T_NEG_PEDIDO_TIPO (TIPOPED_N_CODIGO)
);


--
-- Table structure for table T_NEG_PEDIDO2PEDIDO
--

CREATE TABLE T_NEG_PEDIDO2PEDIDO (
  PEDIDO_N_CODIGO_FROM INTEGER NOT NULL,
  PEDIDO_N_CODIGO_TO INTEGER NOT NULL,
  PRIMARY KEY (PEDIDO_N_CODIGO_FROM,PEDIDO_N_CODIGO_TO)
);


--
-- Table structure for table T_NEG_PEDIDO_DET
--

CREATE TABLE T_NEG_PEDIDO_DET (
  PEDIDO_N_CODIGO INTEGER NOT NULL,
  ARTICULO_N_CODIGO INTEGER NOT NULL,
  DETPED_N_CANTIDAD INTEGER DEFAULT NULL,
  PRIMARY KEY (PEDIDO_N_CODIGO,ARTICULO_N_CODIGO),
  CONSTRAINT FK_T_NEG_PEDIDO_DET FOREIGN KEY (PEDIDO_N_CODIGO) REFERENCES T_NEG_PEDIDO (PEDIDO_N_CODIGO),
  CONSTRAINT FK_T_NEG_PEDIDO_DET2 FOREIGN KEY (ARTICULO_N_CODIGO) REFERENCES T_NEG_ARTICULO (ARTICULO_N_CODIGO)
);


--
-- Table structure for table T_NEG_SOLICITUD
--

CREATE TABLE T_NEG_SOLICITUD (
  SOLICITUD_N_CODIGO INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  SOLICITUD_V_RAZON varchar(100) DEFAULT NULL,
  SOLICITUD_N_RUC varchar(11) DEFAULT NULL,
  SOLICITUD_D_FECHA date DEFAULT NULL,
  SOLICITUD_N_ESTADO INTEGER DEFAULT NULL,
  SOLICITUD_V_EMAIL varchar(50) DEFAULT NULL,
  PRIMARY KEY (SOLICITUD_N_CODIGO)
);


--
-- Table structure for table T_NEG_VENTA_TIPO
--

CREATE TABLE T_NEG_VENTA_TIPO (
  TIPOVEN_N_CODIGO INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  EMPRESA_N_CODIGO INTEGER NOT NULL,
  TIPOVEN_V_DESCRIPCION varchar(50) DEFAULT NULL,
  PRIMARY KEY (TIPOVEN_N_CODIGO),
  CONSTRAINT FK_REL_EMPRESA_TIPOVENTA FOREIGN KEY (EMPRESA_N_CODIGO) REFERENCES T_EMP_EMPRESA (EMPRESA_N_CODIGO)
);
